{% set version = '1.0-5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-relimp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/relimp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/relimp/relimp_{{ version }}.tar.gz
  sha256: acac7cf72ea39916761b51c825db0ffcb2bb1640e0a04086831fb78e9e40b679

build:
  merge_build_host: True  # [win]
  number: 1003
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('relimp')"           # [not win]
    - "\"%R%\" -e \"library('relimp')\""  # [win]

about:
  home: http://warwick.ac.uk/relimp
  license: GPL-2.0-or-later
  summary: Functions to facilitate inference on the relative importance of predictors in a linear
    or generalized linear model, and a couple of useful Tcl/Tk widgets.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
