travis:
  secure:
    BINSTAR_TOKEN: vnEyDShcmEdq8wC06pnEVfQtfCckji3sepZBEvaW7Wq2HQaupaCqGIpvBRtzlguyhsW4ap+NdhOhGh2ZuRjleJKpRxwGytmAsh7DQvA9keCqAyx+NZUVstU34RXWKvguSmjDHyB087ZuDrAceYe4nEuVZiFAcvbcdzRvwvViQRTpUXXOwZL0zuT+Qx+P+yA4oz32TT3I0EdRJVHVszsC0QNFY7hZWvpeNc8Dmoae/GpF5c8Fmfi+3mWwEkhSjFBdYN3Fdl7+1IrPFIVu9fGnGoMYKakiz8LdccVfQVCzB/OioGxdVExhwmfFzkl7uxzhuodXvUI62LlWzUNRpvg4Bwm/LuK/RMB+ER2NVzkAvslc1Idf3SZEaVrJh/0mjHNSkv744VsUocBkpVdWEcjMF0geb8kwGPYGOROqpMkMAkMA05AoAB4HeoBDc1CxFfSXCAVVpxfEUcYsFgQjaOFpPxNiOckuBw6Q1r3I3xQJ0+KcOhX/3xjBAuqKxg4UMlKBbwEqG4mFIbZAHl5EhWO9v9daFoCd7+ygp0jBtyJvPjP2olJL5ynoKx5Mn4RmELD8jH1lkVuSd2joFOohQ6NR7wfla3NlLtcNnMA9znpRpnhlh9YwjbtFjid5Q39uSJ8veei1ogrnhoizOF1jbJDuAufYdOrCbY6/Ocyv7OkENg8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
