travis:
  secure:
    BINSTAR_TOKEN: jwnvoLu1Tz5V/3ySnWjw7ejh8rZV5jR0KOl0x8Sd56VxnIu8lUA89oRlAs8YPXNgGwg1VTS/HKNcWYEHkUHg6z2x2CD1KDw2/ogXM+Fs0afRUndsU62TP1f0YL/XrJQjXE8lf+QOIzWgEVRBlWX/nESKjYscHVgB2414//2LuyOa2PRWM0/iGJoeQu380/5SKf9REsZfyvqb96V/1qJExm5NdOQIgc6edIuz4On8VOm7fSm7ocKBKG3M8ig34TOqHMuzVnv6mjKLArWtcRI2SmoFHmpWxPHSkk3rLrnlZJ1IUDMftLtJEusVgykE/fDCnjgnYPCIGMz/J/LUcRBB/munclFlR4WCRp06/TmjlwK21m6bEvThBkbuCQh6RYgq6NdMTLzjKriye4wiNx0UzmhlzZBuiWXlqdjM1+5YrpOyJOxrO3IvEv3WT4PlCwP3HD1G1rPn3G1KI+9lEZ7TTSlAYaWFGVQaaA8x9xMMt9YHWae1Opqdl0+dPVL2sTWz4Rm56QTHWbWBwNCE98hfPoTFlJi/40EK7oe2DQWfGbNctUfX92ZBJvg0Lk6x01Dv6XwQqjT9vfMqRgWo4c4G2MR9HRSbNXWYccbTAXcpZAYXR2PiWYUl6V7SaQAnG/nS0M+FOVVhsyLJMJJAnSmHW1gthbpRzxXwskOYCRG1O8o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
